services:
  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 8000:80
    networks:
      - mariadb_default
    restart: always
    environment:
      WORDPRESS_DB_HOST: wp-mariadb-1
      WORDPRESS_DB_USER: wp_admin
      WORDPRESS_DB_PASSWORD: wp_admin_password
      WORDPRESS_DB_NAME: wordpress

volumes:
  wp_data:

networks:
  mariadb_default:
    external: true
